eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer:  https://dev-63579389.okta.com/oauth2/default
    audience: api://default      
